/**
 * Generates a PySpark script written for AWS Glue that:
 *   1. Reads each source table via JDBC (Glue's native JDBC connection)
 *   2. For each target collection, joins in "embed" child tables and
 *      collapses them into a nested array field via collect_list(struct(...))
 *   3. Leaves "reference" child tables as their own collections, writing
 *      only the foreign key (no embedding) so they can be looked up
 *      independently at read time
 *   4. Writes each resulting DataFrame to MongoDB using the MongoDB
 *      Spark Connector
 *
 * The generated script is meant to be uploaded as a Glue job script
 * (Glue 4.0+, Spark 3.x) with the MongoDB Spark Connector added as a
 * job dependency (--extra-jars or the connector's Maven coordinates via
 * --additional-python-modules / connector marketplace connection).
 */

const { bsonTypeToSparkType } = require("../bsonTypeMapper");

function pythonStr(value) {
  return `"${String(value).replace(/"/g, '\\"')}"`;
}

// Casts every column of a just-read table to its (possibly user-overridden)
// target BSON type's Spark equivalent, re-aliasing to the same column name
// so nothing downstream (struct field lists, join-key references) needs to
// change. Applied unconditionally to every column on every table read --
// root, embed children, and reference tables -- rather than only when a
// user diverges from the inferred default, so two logically-identical
// columns in different tables don't end up cast vs. not depending on
// whether someone happened to touch a dropdown.
function castSelectLines(varName, table) {
  const castExprs = table.columns.map((c) => {
    const sparkType = bsonTypeToSparkType(c.bsonType);
    return `col(${pythonStr(c.name)}).cast(${pythonStr(sparkType)}).alias(${pythonStr(c.name)})`;
  });
  return `${varName} = ${varName}.select(\n    ${castExprs.join(",\n    ")}\n)`;
}

function generateGlueJob({ jdbc, mongo, schema, mapping, loadMode = "full" }) {
  const tableByName = new Map(schema.tables.map((t) => [t.name, t]));

  const header = `"""
Auto-generated AWS Glue ETL job.
Source: JDBC relational database  ->  Target: MongoDB

Generated by: MongoDB Relational Migrator (Node/React tool)
Do not edit column/table names below without re-running the generator --
they are derived directly from the source schema + mapping you designed.

Load mode: ${loadMode}
${
  loadMode === "incremental"
    ? "Incremental: upserts by primary key (idempotent re-runs -- inserts new\n" +
      "rows, updates changed ones) but does NOT delete target documents whose\n" +
      "source row was deleted, and does NOT reduce how much is read from the\n" +
      "source -- every run still reads the full table via JDBC."
    : "Full: drops/truncates each target collection before writing (the MongoDB\nSpark Connector's default behavior for mode(\"overwrite\"))."
}
"""

import sys
from awsglue.transforms import *
from awsglue.utils import getResolvedOptions
from pyspark.context import SparkContext
from awsglue.context import GlueContext
from awsglue.job import Job
from pyspark.sql.functions import collect_list, struct, col

args = getResolvedOptions(sys.argv, ["JOB_NAME"])
sc = SparkContext()
glueContext = GlueContext(sc)
spark = glueContext.spark_session
job = Job(glueContext)
job.init(args["JOB_NAME"], args)

# ---------------------------------------------------------------------------
# Connection settings
# ---------------------------------------------------------------------------
JDBC_URL = ${pythonStr(jdbc.url)}
JDBC_USER = ${pythonStr(jdbc.user)}
JDBC_PASSWORD_SECRET_NAME = ${pythonStr(jdbc.passwordSecretName || "REPLACE_WITH_SECRETS_MANAGER_NAME")}
JDBC_DRIVER = ${pythonStr(jdbc.driver)}

MONGO_URI = ${pythonStr(mongo.uri)}
MONGO_DATABASE = ${pythonStr(mongo.database)}

# "full" drops/truncates each target collection before writing; "incremental"
# upserts by primary key instead (idempotent re-runs, but doesn't delete
# target documents whose source row was deleted, and doesn't reduce how much
# is read from the source -- every run still reads the full table via JDBC).
LOAD_MODE = ${pythonStr(loadMode)}

# Resolve the JDBC password from AWS Secrets Manager at runtime rather than
# hardcoding it in the script.
import boto3, json as _json
_secrets = boto3.client("secretsmanager")
_secret_value = _secrets.get_secret_value(SecretId=JDBC_PASSWORD_SECRET_NAME)
JDBC_PASSWORD = _json.loads(_secret_value["SecretString"]).get("password")


def read_table(table_name):
    return (
        spark.read.format("jdbc")
        .option("url", JDBC_URL)
        .option("dbtable", table_name)
        .option("user", JDBC_USER)
        .option("password", JDBC_PASSWORD)
        .option("driver", JDBC_DRIVER)
        .load()
    )


def write_to_mongo(df, collection_name, id_field_list=None):
    writer = df.write.format("mongodb")
    if LOAD_MODE == "incremental" and id_field_list:
        # Upsert: replace a document matching id_field_list's value, insert
        # if no match exists (operationType="replace"/upsertDocument=true
        # are the MongoDB Spark Connector's own defaults -- not set here).
        writer = writer.mode("append").option("idFieldList", id_field_list)
    else:
        writer = writer.mode("overwrite")
    (
        writer
        .option("connection.uri", MONGO_URI)
        .option("database", MONGO_DATABASE)
        .option("collection", collection_name)
        .save()
    )

`;

  const collectionBlocks = mapping.collections
    .map((collection) => generateCollectionBlock(collection, tableByName))
    .join("\n\n");

  const footer = `

job.commit()
`;

  return header + collectionBlocks + footer;
}

function generateCollectionBlock(collection, tableByName) {
  const rootVar = toVar(collection.rootTable);
  const rootTable = tableByName.get(collection.rootTable);
  const lines = [];

  lines.push(`# ---------------------------------------------------------------------------`);
  lines.push(`# Collection: ${collection.collectionName}  (root table: ${collection.rootTable})`);
  lines.push(`# ---------------------------------------------------------------------------`);
  lines.push(`${rootVar} = read_table(${pythonStr(collection.rootTable)})`);
  if (rootTable) lines.push(castSelectLines(rootVar, rootTable));

  let currentVar = rootVar;

  // Embeds: read child table, group by FK, collect_list(struct(...)) the
  // non-key columns, then left-join that nested array back onto the root.
  for (const embed of collection.embeds) {
    const childTable = tableByName.get(embed.table);
    if (!childTable) continue;

    const childVar = toVar(embed.table);
    const nestedVar = `${childVar}_nested`;
    const nonKeyCols = childTable.columns
      .filter((c) => c.name !== embed.foreignKey)
      .map((c) => c.name);

    const structFields = nonKeyCols
      .map((c) => `col(${pythonStr(c)}).alias(${pythonStr(c)})`)
      .join(", ");

    lines.push("");
    lines.push(`# Embed "${embed.table}" as "${embed.as}" (${embed.cardinality})`);
    lines.push(`${childVar} = read_table(${pythonStr(embed.table)})`);
    lines.push(castSelectLines(childVar, childTable));

    if (embed.cardinality === "one") {
      // 1:1 or 1:few-but-flattened -> embed as a single nested object per row.
      lines.push(
        `${nestedVar} = ${childVar}.select(col(${pythonStr(embed.foreignKey)}).alias("_join_key"), struct(${structFields}).alias(${pythonStr(embed.as)}))`
      );
    } else {
      // 1:many -> embed as an array of nested objects per row.
      lines.push(
        `${nestedVar} = ${childVar}.groupBy(col(${pythonStr(embed.foreignKey)}).alias("_join_key")).agg(collect_list(struct(${structFields})).alias(${pythonStr(embed.as)}))`
      );
    }

    const joinedVar = `${currentVar}_with_${childVar}`;
    lines.push(
      `${joinedVar} = ${currentVar}.join(${nestedVar}, ${currentVar}[${pythonStr(rootKeyOf(collection))}] == ${nestedVar}["_join_key"], "left").drop("_join_key")`
    );
    currentVar = joinedVar;
  }

  lines.push("");
  lines.push(
    `write_to_mongo(${currentVar}, ${pythonStr(collection.collectionName)}, id_field_list=${pythonStr(idFieldListOf(collection.primaryKey))})`
  );

  // References: written to their own collection, keeping only the FK
  // (no embedding) so they can be looked up independently at read time.
  for (const ref of collection.references) {
    const refTable = tableByName.get(ref.table);
    if (!refTable) continue;

    const refVar = toVar(ref.table);
    lines.push("");
    lines.push(`# Reference "${ref.table}" -> kept as its own collection, linked by "${ref.foreignKey}"`);
    lines.push(`${refVar} = read_table(${pythonStr(ref.table)})`);
    lines.push(castSelectLines(refVar, refTable));
    lines.push(
      `write_to_mongo(${refVar}, ${pythonStr(pluralizeForVar(ref.table))}, id_field_list=${pythonStr(idFieldListOf(refTable.primaryKey))})`
    );
  }

  return lines.join("\n");
}

function rootKeyOf(collection) {
  return collection.primaryKey && collection.primaryKey.length
    ? collection.primaryKey[0]
    : "id";
}

// Comma-joined primary key column(s) for the MongoDB Spark Connector's
// idFieldList write option, used only in incremental (upsert) load mode.
function idFieldListOf(primaryKey) {
  return primaryKey && primaryKey.length ? primaryKey.join(",") : "id";
}

function toVar(tableName) {
  return `df_${tableName.replace(/[^a-zA-Z0-9_]/g, "_")}`;
}

function pluralizeForVar(name) {
  if (name.endsWith("s")) return name;
  return `${name}s`;
}

module.exports = { generateGlueJob };
