/**
 * Generates a PySpark script written for AWS Glue that:
 *   1. Reads each source table via JDBC (Glue's native JDBC connection)
 *   2. For each target collection, joins in "embed" child tables and
 *      collapses them into a nested array field via collect_list(struct(...))
 *   3. Leaves "reference" child tables as their own collections, writing
 *      only the foreign key (no embedding) so they can be looked up
 *      independently at read time
 *   4. Writes each resulting DataFrame to MongoDB using the MongoDB
 *      Spark Connector
 *
 * The generated script is meant to be uploaded as a Glue job script
 * (Glue 4.0+, Spark 3.x) with the MongoDB Spark Connector added as a
 * job dependency (--extra-jars or the connector's Maven coordinates via
 * --additional-python-modules / connector marketplace connection).
 */

function pythonStr(value) {
  return `"${String(value).replace(/"/g, '\\"')}"`;
}

function generateGlueJob({ jdbc, mongo, schema, mapping }) {
  const tableByName = new Map(schema.tables.map((t) => [t.name, t]));

  const header = `"""
Auto-generated AWS Glue ETL job.
Source: JDBC relational database  ->  Target: MongoDB

Generated by: MongoDB Relational Migrator (Node/React tool)
Do not edit column/table names below without re-running the generator --
they are derived directly from the source schema + mapping you designed.
"""

import sys
from awsglue.transforms import *
from awsglue.utils import getResolvedOptions
from pyspark.context import SparkContext
from awsglue.context import GlueContext
from awsglue.job import Job
from pyspark.sql.functions import collect_list, struct, col

args = getResolvedOptions(sys.argv, ["JOB_NAME"])
sc = SparkContext()
glueContext = GlueContext(sc)
spark = glueContext.spark_session
job = Job(glueContext)
job.init(args["JOB_NAME"], args)

# ---------------------------------------------------------------------------
# Connection settings
# ---------------------------------------------------------------------------
JDBC_URL = ${pythonStr(jdbc.url)}
JDBC_USER = ${pythonStr(jdbc.user)}
JDBC_PASSWORD_SECRET_NAME = ${pythonStr(jdbc.passwordSecretName || "REPLACE_WITH_SECRETS_MANAGER_NAME")}
JDBC_DRIVER = ${pythonStr(jdbc.driver)}

MONGO_URI = ${pythonStr(mongo.uri)}
MONGO_DATABASE = ${pythonStr(mongo.database)}

# Resolve the JDBC password from AWS Secrets Manager at runtime rather than
# hardcoding it in the script.
import boto3, json as _json
_secrets = boto3.client("secretsmanager")
_secret_value = _secrets.get_secret_value(SecretId=JDBC_PASSWORD_SECRET_NAME)
JDBC_PASSWORD = _json.loads(_secret_value["SecretString"]).get("password")


def read_table(table_name):
    return (
        spark.read.format("jdbc")
        .option("url", JDBC_URL)
        .option("dbtable", table_name)
        .option("user", JDBC_USER)
        .option("password", JDBC_PASSWORD)
        .option("driver", JDBC_DRIVER)
        .load()
    )


def write_to_mongo(df, collection_name):
    (
        df.write.format("mongodb")
        .mode("overwrite")
        .option("connection.uri", MONGO_URI)
        .option("database", MONGO_DATABASE)
        .option("collection", collection_name)
        .save()
    )

`;

  const collectionBlocks = mapping.collections
    .map((collection) => generateCollectionBlock(collection, tableByName))
    .join("\n\n");

  const footer = `

job.commit()
`;

  return header + collectionBlocks + footer;
}

function generateCollectionBlock(collection, tableByName) {
  const rootVar = toVar(collection.rootTable);
  const lines = [];

  lines.push(`# ---------------------------------------------------------------------------`);
  lines.push(`# Collection: ${collection.collectionName}  (root table: ${collection.rootTable})`);
  lines.push(`# ---------------------------------------------------------------------------`);
  lines.push(`${rootVar} = read_table(${pythonStr(collection.rootTable)})`);

  let currentVar = rootVar;

  // Embeds: read child table, group by FK, collect_list(struct(...)) the
  // non-key columns, then left-join that nested array back onto the root.
  for (const embed of collection.embeds) {
    const childTable = tableByName.get(embed.table);
    if (!childTable) continue;

    const childVar = toVar(embed.table);
    const nestedVar = `${childVar}_nested`;
    const nonKeyCols = childTable.columns
      .filter((c) => c.name !== embed.foreignKey)
      .map((c) => c.name);

    const structFields = nonKeyCols
      .map((c) => `col(${pythonStr(c)}).alias(${pythonStr(c)})`)
      .join(", ");

    lines.push("");
    lines.push(`# Embed "${embed.table}" as "${embed.as}" (${embed.cardinality})`);
    lines.push(`${childVar} = read_table(${pythonStr(embed.table)})`);

    if (embed.cardinality === "one") {
      // 1:1 or 1:few-but-flattened -> embed as a single nested object per row.
      lines.push(
        `${nestedVar} = ${childVar}.select(col(${pythonStr(embed.foreignKey)}).alias("_join_key"), struct(${structFields}).alias(${pythonStr(embed.as)}))`
      );
    } else {
      // 1:many -> embed as an array of nested objects per row.
      lines.push(
        `${nestedVar} = ${childVar}.groupBy(col(${pythonStr(embed.foreignKey)}).alias("_join_key")).agg(collect_list(struct(${structFields})).alias(${pythonStr(embed.as)}))`
      );
    }

    const joinedVar = `${currentVar}_with_${childVar}`;
    lines.push(
      `${joinedVar} = ${currentVar}.join(${nestedVar}, ${currentVar}[${pythonStr(rootKeyOf(collection))}] == ${nestedVar}["_join_key"], "left").drop("_join_key")`
    );
    currentVar = joinedVar;
  }

  lines.push("");
  lines.push(`write_to_mongo(${currentVar}, ${pythonStr(collection.collectionName)})`);

  // References: written to their own collection, keeping only the FK
  // (no embedding) so they can be looked up independently at read time.
  for (const ref of collection.references) {
    const refVar = toVar(ref.table);
    lines.push("");
    lines.push(`# Reference "${ref.table}" -> kept as its own collection, linked by "${ref.foreignKey}"`);
    lines.push(`${refVar} = read_table(${pythonStr(ref.table)})`);
    lines.push(`write_to_mongo(${refVar}, ${pythonStr(pluralizeForVar(ref.table))})`);
  }

  return lines.join("\n");
}

function rootKeyOf(collection) {
  return collection.primaryKey && collection.primaryKey.length
    ? collection.primaryKey[0]
    : "id";
}

function toVar(tableName) {
  return `df_${tableName.replace(/[^a-zA-Z0-9_]/g, "_")}`;
}

function pluralizeForVar(name) {
  if (name.endsWith("s")) return name;
  return `${name}s`;
}

module.exports = { generateGlueJob };
