/**
 * Generates a PySpark script written for AWS Glue that:
 *   1. Reads each source table via JDBC (Glue's native JDBC connection)
 *   2. For each target collection, joins in "embed" child tables and
 *      collapses them into a nested array field via collect_list(struct(...))
 *   3. Leaves "reference" child tables as their own collections, writing
 *      only the foreign key (no embedding) so they can be looked up
 *      independently at read time
 *   4. Writes each resulting DataFrame to MongoDB using the MongoDB
 *      Spark Connector
 *
 * The generated script is meant to be uploaded as a Glue job script
 * (Glue 4.0+, Spark 3.x) with the MongoDB Spark Connector added as a
 * job dependency (--extra-jars or the connector's Maven coordinates via
 * --additional-python-modules / connector marketplace connection).
 */

function pythonStr(value) {
  return `"${String(value).replace(/"/g, '\\"')}"`;
}

function generateGlueJob({ jdbc, mongo, schema, mapping, loadStrategy = { type: "full" } }) {
  const tableByName = new Map(schema.tables.map((t) => [t.name, t]));
  const isIncremental = loadStrategy.type === "incremental";
  const watermarkColumn = loadStrategy.watermarkColumn || null;
  // Where the last-seen watermark value per table is persisted between runs.
  // s3://bucket/key.json for a real deployment, or a local path for the
  // local-Docker test harness.
  const statePath = loadStrategy.statePath || "./.local-test/watermark_state.json";

  const header = `"""
Auto-generated AWS Glue ETL job.
Source: JDBC relational database  ->  Target: MongoDB
Load strategy: ${isIncremental ? `INCREMENTAL (watermark column: "${watermarkColumn}")` : "FULL"}

Generated by: MongoDB Relational Migrator (Node/React tool)
Do not edit column/table names below without re-running the generator --
they are derived directly from the source schema + mapping you designed.
"""

import sys
from awsglue.transforms import *
from awsglue.utils import getResolvedOptions
from pyspark.context import SparkContext
from awsglue.context import GlueContext
from awsglue.job import Job
from pyspark.sql.functions import collect_list, struct, col, expr, current_date, current_timestamp, max as spark_max

args = getResolvedOptions(sys.argv, ["JOB_NAME"])
sc = SparkContext()
glueContext = GlueContext(sc)
spark = glueContext.spark_session
job = Job(glueContext)
job.init(args["JOB_NAME"], args)

# ---------------------------------------------------------------------------
# Connection settings
# ---------------------------------------------------------------------------
JDBC_URL = ${pythonStr(jdbc.url)}
JDBC_USER = ${pythonStr(jdbc.user)}
JDBC_PASSWORD_SECRET_NAME = ${pythonStr(jdbc.passwordSecretName || "REPLACE_WITH_SECRETS_MANAGER_NAME")}
JDBC_DRIVER = ${pythonStr(jdbc.driver)}

MONGO_URI = ${pythonStr(mongo.uri)}
MONGO_DATABASE = ${pythonStr(mongo.database)}

# Resolve the JDBC password from AWS Secrets Manager at runtime rather than
# hardcoding it in the script.
import boto3, json as _json
_secrets = boto3.client("secretsmanager")
_secret_value = _secrets.get_secret_value(SecretId=JDBC_PASSWORD_SECRET_NAME)
JDBC_PASSWORD = _json.loads(_secret_value["SecretString"]).get("password")

# ---------------------------------------------------------------------------
# Load strategy: ${isIncremental ? "INCREMENTAL" : "FULL"}
# ---------------------------------------------------------------------------
import os
LOAD_STRATEGY = ${pythonStr(loadStrategy.type)}
WATERMARK_COLUMN = ${pythonStr(watermarkColumn || "")}
STATE_PATH = ${pythonStr(statePath)}


def _load_state():
    """Reads the {table_name: last_watermark_value} map from S3 (s3://...)
    or a local path, so an incremental run only pulls rows newer than the
    last successful run. Returns {} the first time (falls back to a full
    read per table)."""
    if not LOAD_STRATEGY == "incremental":
        return {}
    if STATE_PATH.startswith("s3://"):
        bucket, _, key = STATE_PATH[5:].partition("/")
        s3 = boto3.client("s3")
        try:
            obj = s3.get_object(Bucket=bucket, Key=key)
            return _json.loads(obj["Body"].read())
        except s3.exceptions.NoSuchKey:
            return {}
        except s3.exceptions.ClientError:
            return {}
    if os.path.exists(STATE_PATH):
        with open(STATE_PATH) as f:
            return _json.load(f)
    return {}


def _save_state(state):
    body = _json.dumps(state).encode("utf-8")
    if STATE_PATH.startswith("s3://"):
        bucket, _, key = STATE_PATH[5:].partition("/")
        boto3.client("s3").put_object(Bucket=bucket, Key=key, Body=body)
        return
    os.makedirs(os.path.dirname(STATE_PATH) or ".", exist_ok=True)
    with open(STATE_PATH, "wb") as f:
        f.write(body)


_STATE = _load_state()


def read_table(table_name, watermark_column=None):
    reader = (
        spark.read.format("jdbc")
        .option("url", JDBC_URL)
        .option("user", JDBC_USER)
        .option("password", JDBC_PASSWORD)
        .option("driver", JDBC_DRIVER)
    )
    if LOAD_STRATEGY == "incremental" and watermark_column:
        last_value = _STATE.get(table_name)
        if last_value:
            subquery = (
                f"(SELECT * FROM {table_name} "
                f"WHERE {watermark_column} > '{last_value}') AS t"
            )
            return reader.option("dbtable", subquery).load()
    return reader.option("dbtable", table_name).load()


def record_watermark(df, table_name, watermark_column):
    """Call right after read_table() for a table that has the watermark
    column, so the next incremental run starts from the newest row seen
    in *this* run (not the write side, which may have dropped columns)."""
    if LOAD_STRATEGY != "incremental" or not watermark_column:
        return
    row = df.agg(spark_max(col(watermark_column)).alias("_wm")).collect()[0]
    if row["_wm"] is not None:
        _STATE[table_name] = str(row["_wm"])
        _save_state(_STATE)


def write_to_mongo(df, collection_name):
    (
        df.write.format("mongodb")
        .mode("overwrite" if LOAD_STRATEGY == "full" else "append")
        .option("connection.uri", MONGO_URI)
        .option("database", MONGO_DATABASE)
        .option("collection", collection_name)
        .save()
    )

`;

  const collectionBlocks = mapping.collections
    .map((collection) => generateCollectionBlock(collection, tableByName, { isIncremental, watermarkColumn }))
    .join("\n\n");

  const footer = `

job.commit()
`;

  return header + collectionBlocks + footer;
}

function generateCollectionBlock(collection, tableByName, loadCtx = { isIncremental: false, watermarkColumn: null }) {
  const rootVar = toVar(collection.rootTable);
  const lines = [];

  function watermarkArgFor(tableName) {
    if (!loadCtx.isIncremental || !loadCtx.watermarkColumn) return null;
    const table = tableByName.get(tableName);
    const hasColumn = table && table.columns.some((c) => c.name === loadCtx.watermarkColumn);
    return hasColumn ? loadCtx.watermarkColumn : null;
  }

  function emitRead(varName, tableName) {
    const wmColumn = watermarkArgFor(tableName);
    if (wmColumn) {
      lines.push(`${varName} = read_table(${pythonStr(tableName)}, watermark_column=${pythonStr(wmColumn)})`);
      lines.push(`record_watermark(${varName}, ${pythonStr(tableName)}, ${pythonStr(wmColumn)})`);
    } else {
      lines.push(`${varName} = read_table(${pythonStr(tableName)})`);
    }
  }

  lines.push(`# ---------------------------------------------------------------------------`);
  lines.push(`# Collection: ${collection.collectionName}  (root table: ${collection.rootTable})`);
  lines.push(`# ---------------------------------------------------------------------------`);
  emitRead(rootVar, collection.rootTable);

  let currentVar = rootVar;

  // Embeds: read child table, group by FK, collect_list(struct(...)) the
  // non-key columns, then left-join that nested array back onto the root.
  for (const embed of collection.embeds) {
    const childTable = tableByName.get(embed.table);
    if (!childTable) continue;

    const childVar = toVar(embed.table);
    const nestedVar = `${childVar}_nested`;
    const nonKeyCols = childTable.columns
      .filter((c) => c.name !== embed.foreignKey)
      .map((c) => c.name);

    const structFields = nonKeyCols
      .map((c) => `col(${pythonStr(c)}).alias(${pythonStr(c)})`)
      .join(", ");

    lines.push("");
    lines.push(`# Embed "${embed.table}" as "${embed.as}" (${embed.cardinality})`);
    emitRead(childVar, embed.table);

    if (embed.cardinality === "one") {
      // 1:1 or 1:few-but-flattened -> embed as a single nested object per row.
      lines.push(
        `${nestedVar} = ${childVar}.select(col(${pythonStr(embed.foreignKey)}).alias("_join_key"), struct(${structFields}).alias(${pythonStr(embed.as)}))`
      );
    } else {
      // 1:many -> embed as an array of nested objects per row.
      lines.push(
        `${nestedVar} = ${childVar}.groupBy(col(${pythonStr(embed.foreignKey)}).alias("_join_key")).agg(collect_list(struct(${structFields})).alias(${pythonStr(embed.as)}))`
      );
    }

    const joinedVar = `${currentVar}_with_${childVar}`;
    lines.push(
      `${joinedVar} = ${currentVar}.join(${nestedVar}, ${currentVar}[${pythonStr(rootKeyOf(collection))}] == ${nestedVar}["_join_key"], "left").drop("_join_key")`
    );
    currentVar = joinedVar;
  }

  // Computed columns: user-defined derived fields, e.g. combining two
  // source columns ("expression") or stamping the load time ("default_*").
  for (const cc of collection.computedColumns || []) {
    lines.push("");
    if (cc.kind === "default_current_date") {
      lines.push(`# Computed column "${cc.name}": defaults to the current date at load time`);
      lines.push(`${currentVar} = ${currentVar}.withColumn(${pythonStr(cc.name)}, current_date())`);
    } else if (cc.kind === "default_current_timestamp") {
      lines.push(`# Computed column "${cc.name}": defaults to the current timestamp at load time`);
      lines.push(`${currentVar} = ${currentVar}.withColumn(${pythonStr(cc.name)}, current_timestamp())`);
    } else {
      // "expression" -- a Spark SQL expression string the user typed, e.g.
      // "first_name || ' ' || last_name" or "price * quantity".
      lines.push(`# Computed column "${cc.name}": ${cc.expression}`);
      lines.push(
        `${currentVar} = ${currentVar}.withColumn(${pythonStr(cc.name)}, expr(${pythonStr(cc.expression || "NULL")}))`
      );
    }
  }

  lines.push("");
  lines.push(`write_to_mongo(${currentVar}, ${pythonStr(collection.collectionName)})`);

  // References: written to their own collection, keeping only the FK
  // (no embedding) so they can be looked up independently at read time.
  for (const ref of collection.references) {
    const refVar = toVar(ref.table);
    lines.push("");
    lines.push(`# Reference "${ref.table}" -> kept as its own collection, linked by "${ref.foreignKey}"`);
    emitRead(refVar, ref.table);
    lines.push(`write_to_mongo(${refVar}, ${pythonStr(pluralizeForVar(ref.table))})`);
  }

  return lines.join("\n");
}

function rootKeyOf(collection) {
  return collection.primaryKey && collection.primaryKey.length
    ? collection.primaryKey[0]
    : "id";
}

function toVar(tableName) {
  return `df_${tableName.replace(/[^a-zA-Z0-9_]/g, "_")}`;
}

function pluralizeForVar(name) {
  if (name.endsWith("s")) return name;
  return `${name}s`;
}

module.exports = { generateGlueJob };
